# -*- coding: utf-8 -*-
"""Gradient Descent Algorithm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zHmlKPIbkOnx2AI-zvEfh1u_37Z-bnfS
"""

import numpy as np
import pandas as pd

m=0
c=0
lr=0.0001
epoch=10000

dataset = pd.read_csv('aimarks2017.csv')
mse_marks = dataset.iloc[:, :-1].values
ese_marks = dataset.iloc[:, -1].values
n=float(len(mse_marks))

x = pd.Series(mse_marks)
y = pd.Series(ese_marks)

r = x.cov(y)/(x.std()*y.std())

beta1 = (r*y.std())/x.std()
beta0 = y.mean()-beta1*x.mean()
print(beta1,beta0)

for i in range(epoch):
  y_pred = mse_marks*m + c
  dm=(-2/n)*sum(mse_marks*(ese_marks-y_pred))
  de=(-2/n)*sum(ese_marks-y_pred)
  m=m-lr*dm
  c=c-lr*de
print(m,c)
